/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_xk_interface
#define DBUS_GLIB_CLIENT_WRAPPERS_com_xk_interface

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_xk_interface_request (DBusGProxy *proxy, const gint IN_arg0, const GArray* IN_arg1, GArray** OUT_arg2, gint* OUT_arg3, GError **error)

{
  return dbus_g_proxy_call (proxy, "Request", error, G_TYPE_INT, IN_arg0, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_arg1, G_TYPE_INVALID, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), OUT_arg2, G_TYPE_INT, OUT_arg3, G_TYPE_INVALID);
}

typedef void (*com_xk_interface_request_reply) (DBusGProxy *proxy, GArray *OUT_arg2, gint OUT_arg3, GError *error, gpointer userdata);

static void
com_xk_interface_request_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  GArray* OUT_arg2;
  gint OUT_arg3;
  dbus_g_proxy_end_call (proxy, call, &error, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), &OUT_arg2, G_TYPE_INT, &OUT_arg3, G_TYPE_INVALID);
  (*(com_xk_interface_request_reply)data->cb) (proxy, OUT_arg2, OUT_arg3, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_xk_interface_request_async (DBusGProxy *proxy, const gint IN_arg0, const GArray* IN_arg1, com_xk_interface_request_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Request", com_xk_interface_request_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INT, IN_arg0, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_arg1, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_xk_interface_call (DBusGProxy *proxy, const char * IN_arg0, char ** OUT_arg1, GError **error)

{
  return dbus_g_proxy_call (proxy, "Call", error, G_TYPE_STRING, IN_arg0, G_TYPE_INVALID, G_TYPE_STRING, OUT_arg1, G_TYPE_INVALID);
}

typedef void (*com_xk_interface_call_reply) (DBusGProxy *proxy, char * OUT_arg1, GError *error, gpointer userdata);

static void
com_xk_interface_call_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_arg1;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_arg1, G_TYPE_INVALID);
  (*(com_xk_interface_call_reply)data->cb) (proxy, OUT_arg1, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_xk_interface_call_async (DBusGProxy *proxy, const char * IN_arg0, com_xk_interface_call_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Call", com_xk_interface_call_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_arg0, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_xk_interface */

G_END_DECLS
